In [38]:
#print(__doc__)

# Code source: Gaël Varoquaux
# Modified for documentation by Jaques Grobler
# License: BSD 3 clause

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn import metrics
from sklearn.model_selection import train_test_split


# import some data to play with
iris = datasets.load_iris()


x_train, x_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.25, random_state=0)


# Create an instance of Logistic Regression Classifier and fit the data.
logreg = LogisticRegression(C=1e5)
logreg.fit(x_train, y_train)

predictions = logreg.predict(x_test)
cm = metrics.confusion_matrix(y_test, predictions)
print(cm)

# Use score method to get accuracy of model
score = logreg.score(x_test, y_test)
print(score)


# 2. Precision Score

pred = logreg.predict_proba(x_test)

print(metrics.log_loss(y_test, pred))

print(metrics.classification_report(y_test, predictions, digits=3))


# Use plot_roc_curve to draw Roc_Curve
#y_test_0 = [y_test[i] for i in [1,2]]
#print(set(y_test_0))
#metrics.plot_roc_curve(logreg, x_test, y_test_0)
#plt.show()

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
0.9736842105263158
0.913159802223634
              precision    recall  f1-score   support

           0      1.000     1.000     1.000        13
           1      1.000     0.938     0.968        16
           2      0.900     1.000     0.947         9

    accuracy                          0.974        38
   macro avg      0.967     0.979     0.972        38
weighted avg      0.976     0.974     0.974        38



/Users/azadeh/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
